# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.selectFolderButton = QtWidgets.QPushButton(MainWindow)
        self.selectFolderButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.selectFolderButton.setObjectName("selectFolderButton")
        self.nextImageButton = QtWidgets.QPushButton(MainWindow)
        self.nextImageButton.setGeometry(QtCore.QRect(110, 260, 181, 23))
        self.nextImageButton.setObjectName("nextImageButton")
        self.imageLabel = QtWidgets.QLabel(MainWindow)
        self.imageLabel.setGeometry(QtCore.QRect(20, 40, 361, 211))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.selectFolderButton.setText(_translate("MainWindow", "Открыть"))
        self.nextImageButton.setText(_translate("MainWindow", "Следующее изображение"))
